### ISSUE TITLE
[Bug report] my module relative path not handled properly

### ISSUE THREAD

**Issue by zhengxsFE** [greedbell/gulp-require-modules#2]
node:  v11.6.0
npm: v6.8.0

gulp:

[15:29:12] CLI version 2.0.1
[15:29:12] Local version 4.0.0

gulp-require-modules: v1.1.3

```text
- distFileDirname: D:\workspace\mtfe\templates\wechat-miniprogram-app-boilerplate\dist\pages\components\button,
 - targetPath: D:\workspace\mtfe\templates\wechat-miniprogram-app-boilerplate\dist\node_modules\miniprogram-plugin-http\dist\lib.common.js
 - relativePath: ../..\..\node_modules\miniprogram-plugin-http\dist\lib.common.js
```

![image](https://user-images.githubusercontent.com/7506913/53226387-d4484f80-36b5-11e9-9b65-f2dcb63e4bdf.png)

![image](https://user-images.githubusercontent.com/7506913/53226448-fcd04980-36b5-11e9-899b-2baff28f146c.png)

my solution:

![image](https://user-images.githubusercontent.com/7506913/53226995-e2976b00-36b7-11e9-9bce-123fc86616c7.png)

I am not good at English. I hope these pictures will help you.

**Comment by greedbell** [comment]
@zhengxsFE Can you create a pull request to fix this?

**Comment by zhengxsFE** [comment]
大佬是中国人？

**Comment by zhengxsFE** [comment]
发了

**Comment by greedbell** [comment]
@zhengxsFE v1.1.4 published
